import fc from 'fast-check'
import { assert, describe, it } from 'vitest'
import { SeedpodsError, getSeedpodsErrorCausesByType } from '../error'
import { validateCookieDomain } from './normalize-cookie-domain'

function normalizeCookieDomain(value: string): string {
  const result = validateCookieDomain(value)

  if (!result.ok) {
    throw new SeedpodsError(result.causes)
  }

  return result.value
}

function expectSeedpodsError(value: string): SeedpodsError {
  try {
    normalizeCookieDomain(value)
    assert.fail('Expected normalizeCookieDomain to throw.')
  } catch (error) {
    assert.instanceOf(error, SeedpodsError)
    return error
  }
}

function assertInvalidDomain(value: string, reason: string): void {
  const error = expectSeedpodsError(value)
  const causes = getSeedpodsErrorCausesByType(error, 'CookieOptionValueInvalid')

  assert.isTrue(
    causes.some((cause) => cause.option === 'domain' && cause.reason.includes(reason)),
    `Expected domain ${JSON.stringify(value)} to fail with reason containing ${JSON.stringify(reason)}. Received ${JSON.stringify(causes)}.`,
  )
}

const alphaNumericCharacters = [...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789']
const labelInteriorCharacters = [...alphaNumericCharacters, '-']

const nrLdhLabelArbitrary = fc
  .oneof(
    fc.constantFrom(...alphaNumericCharacters),
    fc
      .tuple(
        fc.constantFrom(...alphaNumericCharacters),
        fc.array(fc.constantFrom(...labelInteriorCharacters), { maxLength: 61 }),
        fc.constantFrom(...alphaNumericCharacters),
      )
      .map(([first, middle, last]) => `${first}${middle.join('')}${last}`),
  )
  .filter((label) => label.slice(2, 4) !== '--' && label.length <= 63)

const nrLdhDomainArbitrary = fc
  .array(nrLdhLabelArbitrary, { maxLength: 4, minLength: 1 })
  .map((labels) => labels.join('.'))

const uppercaseNrLdhDomainArbitrary = nrLdhDomainArbitrary.map((domain) => domain.toUpperCase())

describe('normalize-cookie-domain', () => {
  it('normalizes valid NR-LDH domains to lowercase ASCII', () => {
    assert.equal(normalizeCookieDomain('Example.COM'), 'example.com')
    assert.equal(normalizeCookieDomain('3Com.Example'), '3com.example')
    assert.equal(normalizeCookieDomain('.Example.COM'), 'example.com')
  })

  it('accepts valid A-labels and normalizes them to lowercase', () => {
    assert.equal(normalizeCookieDomain('xn--bcher-kva.example'), 'xn--bcher-kva.example')
    assert.equal(normalizeCookieDomain('XN--BCHER-KVA.EXAMPLE'), 'xn--bcher-kva.example')
  })

  it('rejects empty and structurally invalid domains', () => {
    assertInvalidDomain('', 'must not be empty')
    assertInvalidDomain('.', 'must not be empty after removing a leading "."')
    assertInvalidDomain('example.com.', 'must not end with "."')
    assertInvalidDomain('example..com', 'empty domain label')
    assertInvalidDomain('..example.com', 'empty domain label')
    assertInvalidDomain('-example.com', 'not NR-LDH or a valid A-label')
    assertInvalidDomain('example-.com', 'not NR-LDH or a valid A-label')
    assertInvalidDomain('exa mple.com', 'not NR-LDH or a valid A-label')
    assertInvalidDomain('_service.example', 'not NR-LDH or a valid A-label')
    assertInvalidDomain(`${'a'.repeat(64)}.example`, 'not NR-LDH or a valid A-label')
  })

  it('rejects Unicode labels in Mode A', () => {
    assertInvalidDomain('bücher.example', 'must contain only ASCII labels')
  })

  it('rejects fake and malformed A-labels', () => {
    assertInvalidDomain('xn--a.example', 'fake A-label')
    assertInvalidDomain('xn--.example', 'valid LDH label')
    assertInvalidDomain('xn--bad_.example', 'valid LDH label')
    assertInvalidDomain('xn---7a.example', 'fake A-label')
  })

  it('rejects IP literals', () => {
    assertInvalidDomain('127.0.0.1', 'must not be an IP literal')
    assertInvalidDomain('::1', 'must not be an IP literal')
    assertInvalidDomain('[::1]', 'must not be an IP literal')
  })

  it('accepts valid NR-LDH domains generated by properties', () => {
    fc.assert(
      fc.property(uppercaseNrLdhDomainArbitrary, (domain) => {
        assert.equal(normalizeCookieDomain(domain), domain.toLowerCase())
      }),
    )
  })

  it('ignores a single leading dot for valid generated domains', () => {
    fc.assert(
      fc.property(nrLdhDomainArbitrary, (domain) => {
        assert.equal(normalizeCookieDomain(`.${domain}`), domain.toLowerCase())
      }),
    )
  })

  it('rejects generated IPv4 literals', () => {
    const ipv4Arbitrary = fc
      .tuple(
        fc.integer({ max: 255, min: 0 }),
        fc.integer({ max: 255, min: 0 }),
        fc.integer({ max: 255, min: 0 }),
        fc.integer({ max: 255, min: 0 }),
      )
      .map((parts) => parts.join('.'))

    fc.assert(
      fc.property(ipv4Arbitrary, (address) => {
        assertInvalidDomain(address, 'must not be an IP literal')
      }),
    )
  })

  it('rejects generated domains with invalid reserved-LDH labels', () => {
    const invalidReservedLdhLabelArbitrary = fc
      .tuple(
        fc.constantFrom(...alphaNumericCharacters),
        fc.constantFrom(...alphaNumericCharacters),
        fc.constant('-'),
        fc.constant('-'),
        fc.array(fc.constantFrom(...labelInteriorCharacters), { maxLength: 10 }),
      )
      .map(([a, b, c, d, rest]) => `${a}${b}${c}${d}${rest.join('')}`)
      .filter((label) => !label.toLowerCase().startsWith('xn--'))

    fc.assert(
      fc.property(invalidReservedLdhLabelArbitrary, (label) => {
        assertInvalidDomain(`${label}.example`, 'not NR-LDH or a valid A-label')
      }),
    )
  })

  it('preserves no hidden normalization for already-valid ASCII path-like separators in labels', () => {
    const invalidCharactersArbitrary = fc.constantFrom('/', ':', ';', '[', ']', '@')

    fc.assert(
      fc.property(nrLdhLabelArbitrary, invalidCharactersArbitrary, (label, invalidCharacter) => {
        assertInvalidDomain(`${label}${invalidCharacter}example`, 'not NR-LDH or a valid A-label')
      }),
    )
  })

  it('keeps valid ASCII output unchanged under repeated normalization', () => {
    fc.assert(
      fc.property(nrLdhDomainArbitrary, (domain) => {
        const normalized = normalizeCookieDomain(domain)
        assert.equal(normalizeCookieDomain(normalized), normalized)
      }),
    )
  })

  it('rejects generated Unicode-containing labels', () => {
    const unicodeDomainArbitrary = fc
      .tuple(fc.constant('bücher'), fc.array(nrLdhLabelArbitrary, { maxLength: 2, minLength: 0 }))
      .map(([head, rest]) => [head, ...rest].join('.'))

    fc.assert(
      fc.property(unicodeDomainArbitrary, (domain) => {
        assertInvalidDomain(domain, 'must contain only ASCII labels')
      }),
    )
  })
})
